### ISSUE TITLE
Cloudflare proxying doesn't make sense

### ISSUE THREAD

**Issue by bsnts** [DennisKidman/io.day#4]
Hi,

Proxying DNS records through Cloudflare doesn't make sense - anyone can just find this repository and look at the IP address behind the subdomain. If I remember correctly, that would remove any benefit proxying would provide. Right?

**Comment by DennisKidman** [comment]
Hello,

When you use Cloudflare as a proxy, it hides the real address of your server from the public and replaces it with Cloudflare's address. This is helpful for protecting your server from attacks by bad guys.

However, if the real address of your server is already known to the public, then there may not be many benefits to using Cloudflare as a proxy. This is because anyone can bypass the Cloudflare proxy and connect directly to your server.

That said, there are other things that Cloudflare can do to help your website run faster and be more secure, like caching, SSL encryption, and firewall protection. So, whether or not using Cloudflare as a proxy is a good idea depends on your specific needs and circumstances.

I hope this explanation helps! Let me know if you have any other questions.

**Comment by bsnts** [comment]
Thank you! That's a very good explanation.
